[workspace]
resolver = "2"
members = [
    "src/cfapi",
    "src/cfvhub",
]
default-members = [
    "src/cfvhub",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

