#ifndef CFAPI_COMMANDS_H
#define CFAPI_COMMANDS_H

/**
* Commands
*/
namespace cfapi
{
	/**
	* Commands that can be used for a request
	*/
	enum Commands
	{
		SUBSCRIBE=0,
		UNSUBSCRIBE=1,
		QUERYDEPTH=2,
		QUERYSNAP=3,
		QUERYWILDCARD=4,
		QUERYDEPTHANDSUBSCRIBE=5,
		QUERYSNAPANDSUBSCRIBE=6,
		LISTENUMERATION=7,
		LISTAVAILABLETOKENS=8,
		LISTADMINISTRATIONINFO=9,
		LISTEXTENDEDEXCHANGEINFO=10,
		SELECTUSERFILTERTOKENS=11,
		LISTSUBSCRIBEDSYMBOLS=12,
		QUERYXREF=13,
		LISTUSERPERMISSION=14,
		GETACTIVECLIENTSINFO=15,
		GETALLUSERS=16,
		SETCONFLATIONINTERVAL=17,
		SUBSCRIBEWILDCARD=18,
		QUERYSNAPANDSUBSCRIBEWILDCARD=19,
		UNSUBSCRIBEWILDCARD=20,
		ADDALTERNATEINDEX=21
	};

}

#endif
