#ifndef CFAPI_MESSAGEEVENTHANDLER_H
#define CFAPI_MESSAGEEVENTHANDLER_H

#include "MessageEvent.h"
#include "../data/MessageReader.h"

namespace cfapi
{
	/**
	* An object that registers to be notified of events generated by receiving a message
	*/

	class MessageEventHandler
	{
		public:
			virtual ~MessageEventHandler() {}
			/**
			* 
			* @param event
			*            carries the fired response event<br>
			*            Note the state of this event is not preserved after return from this function.
			*/
			virtual void onMessageEvent(const MessageEvent& event) = 0;

	};

}

#endif
